# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20150816_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='alpha_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='alpha_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='beta_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='beta_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='caryophyllene_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='caryophyllene_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='cohumulone_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='cohumulone_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='country',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='dealer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='decay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='farnesene_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='farnesene_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='hopoil_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='hopoil_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='humulene_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='humulene_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='kind',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='myrcene_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='myrcene_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='stability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hop',
            name='taste',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='malt',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='malt',
            name='dealer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='malt',
            name='max_dump',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='malt',
            name='moisture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='malt',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='malt',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
